### ISSUE TITLE
0.13文档更新

### ISSUE THREAD

**Issue by demohi** [reactjs-cn/react-docs#7]

**Comment by yibuyisheng** [comment]
谢谢您对项目的关注。

目前此项目中主要翻译 docs 目录下面的文档。

我大致看了下官网 docs 目录下的 md 文件，似乎没有关于 0.13 版本的变动。
我们可能会选择性地翻译其他重要的文档。

如果您觉得某篇文档不错，可以在 issue 中提出来让我们翻译。

**Comment by demohi** [comment]
:+1:   辛苦你们的翻译

我觉得可以先把下载链接等和版本号相关的内容修改一下
